FROM golang:1.16-alpine as build-stage
WORKDIR /usr/src/app
COPY . .

ENV CGO_ENABLED=0

RUN go build && adduser --disabled-password appuser


FROM scratch

ENV REQUEST_ORIGIN=/

COPY --from=build-stage /usr/src/app/server /usr/src/app/server
COPY --from=build-stage /etc/passwd /etc/passwd

USER appuser

EXPOSE 8080

CMD ["/usr/src/app/server"]