FROM node:16-alpine as build-stage
WORKDIR /usr/src/app
COPY . .

RUN npm ci && npm run build


FROM node:16-alpine
ENV REACT_APP_BACKEND_URL=/api/
WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/build /usr/src/app/build

RUN npm install -g serve && adduser --disabled-password appuser

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]