FROM node:16-alpine

ENV REACT_APP_BACKEND_URL=/api/

WORKDIR /usr/src/app

COPY . .

RUN npm ci && \
    npm run build && \
    npm install -g serve && \
    npm prune --production && \
    adduser --disabled-password appuser

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]